### ISSUE TITLE
Deprecate unused `FileID` fields in contract operations, fix documentation

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-protobufs#102]
### Description

The init code used to create a contract is in the file referenced by the `FileID` in the `ContractCreateTransactionBody`. 

However, the resulting bytecode is immutable, and not stored at the original `FileID` (or any `FileID`).

So we should deprecate the `FileID` in the `ContractGetInfo` and `ContractUpdateTransactionBody`.

**Comment by jsync-swirlds** [comment]
Stale.  Please reopen if still needed.
