### ISSUE TITLE
HIP-32 Add additional response codes for extending alias support

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-protobufs#134]
For HIP-32, extending alias support to all transactions and queries, we need proper response codes to be returned when
1. Invalid proxy account ID ->  `INVALID_PROXY_ACCOUNT_ID`
2. Invalid transfer account ID ->  `INVALID_TRANSFER_ACCOUNT_ID`
3. Invalid Fee collector account ID  -> `INVALID_FEE_COLLECTOR_ACCOUNT_ID`
4. Invalid auto renew account ID -> `INVALID_AUTORENEW_ACCOUNT_ID`

**Comment by jsync-swirlds** [comment]
Stale.  Please reopen if still needed.
