### ISSUE TITLE
Review transactions/queries that haven't been implemented 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-protobufs#159]
### Problem

- [ ] crypto add live hash
- [ ] crypto delete live hash
- [ ] crypto get live hash
- [ ] get by key
- [ ] crypto get stakers
- [ ] token get nft infos
- [ ] token get account nft infos
- [ ] get fast transaction record
- [ ] crypto get stakers

### Solution

TBD

**Comment by jsync-swirlds** [comment]
Stale.  Please reopen if still needed.
