### ISSUE TITLE
Add alpha tag to versions that are deployed on previewnet

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-protobufs#18]
Example:

previewnet: 0.13.0-alpha
testnet/mainnet: 0.13.0

**Comment by steven-sheehy** [comment]
Previewnet doesn't have to have _only_ alpha tags. Basically all tags should go to previewnet (alpha, beta, rc, GA) while only GA should go to testnet and mainnet. As a release line works its way through the stages of stability, previewnet as the bleeding edge should get them all. That includes the GA release until the next alpha tag is available.

**Comment by SimiHunjan** [comment]
That makes sense, but how does a user know which version is on previewnet vs. testnet/mainnet in that tagging model? If previewnet has GA tag and so does testnet/mainnet how do you know which network it applies to? What tag triggers the deployment to previewnet? Right now looking at the tags/branches I don't know what is on previewnet.

**Comment by steven-sheehy** [comment]
They can utilize https://github.com/hashgraph/hedera-protobufs/blob/main/services/NetworkGetVersionInfo.proto

All tags automatically are deployed to previewnet right now.

**Comment by SimiHunjan** [comment]
Right, if you query the network that can be used. I was just thinking from the perspective of visiting the repo itself that there is no way to tell what version is on previewnet vs. testnet/mainnet.

**Comment by SimiHunjan** [comment]
Also just tried the query on testnet and it looks like its's not supported yet?

`Exception in thread "main" com.hedera.hashgraph.sdk.PrecheckStatusException: failed pre-check with the status NOT_SUPPORTED`

**Comment by steven-sheehy** [comment]
Ah, I checked with Nosh and it seems it isn't actually implemented. We should add a note to the protobuf that it's not implemented. Or even better, delete it along with any other API that isn't implemented (live hash anyone?).

As for your other point, I think we just need better visibility into what the version is on those environments. For testnet and mainnet, their versions are on status.hedera.com and their deployment is announced in upgrade emails. For previewnet, the version is missing on status.hedera.com and there's no emails. We should fix the status page to include the version.

**Comment by SimiHunjan** [comment]
Status page fixed to include the version available on previewnet and will be automated in the future. https://status.hedera.com
