### ISSUE TITLE
Removing unsupported proto files from the repo

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-protobufs#196]
### Problem

A discussion on Discord brought to attention that some old proto files haven't been pulled out of the repo despite this not being supported by the network.

https://github.com/hashgraph/hedera-protobufs/blob/main/services/crypto_add_live_hash.proto

### Solution

- Remove old protos

**Comment by steven-sheehy** [comment]
Duplicate of https://github.com/hashgraph/hedera-protobufs/issues/159

**Comment by jsync-swirlds** [comment]
Stale.  Please reopen if still needed.
