### ISSUE TITLE
Need to release officially

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-protobufs#251]
### Problem

- Its latest release is v0.20.0 which was released about a year ago. 
- By the way, the tag for this repository has v0.31.0 as the latest one which was released 2 months ago.

### Solution

- hedera-protobufs should release the latest one officially.
- And then hedera-protobufs-[language] repositories should synchronize with it. (e.g. hedera-protobufs-swift, hedera-protobufs-java)

### Alternatives

-

**Comment by jsync-swirlds** [comment]
Stale.  Please reopen if still needed.
