### ISSUE TITLE
Add a new field in `EthereumTransactionBody` for additional non-gas related costs

### ISSUE THREAD

**Issue by dimitar-dinev** [hashgraph/hedera-protobufs#254]
### Description
With the addition of hollow accounts by HIP-583, we want relayers to be able to specify the allowance they are willing to give for the costs of hollow account creation. Due to security reasons, the currently existing `max_gas_allowance` field cannot be used for this purpose.

### Solution
Add a new field for additional non-gas costs allowance in `EthereumTransactionBody` definition.

**Comment by jsync-swirlds** [comment]
Stale.  Please reopen if still needed.
