### ISSUE TITLE
Clean up (NOT SUPPORTED)

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/hedera-protobufs#256]
### Description

There are a number places that have historical API that is marked as `(NOT SUPPORTED)` or `(NOT CURRENTLY SUPPORTED)`. They are not deprecated as well so are getting generated into SDKs. We should remove all of these is there is no chance they will be supported. The specific cases are: 

**basic_types.proto -> Key**
```
       /**
         * (NOT SUPPORTED) RSA-3072 public key bytes
         */
        bytes RSA_3072 = 3;

        /**
         * (NOT SUPPORTED) ECDSA with the p-384 curve public key bytes
         */
        bytes ECDSA_384 = 4;
```
These fields will need to deprecated then after a release they can go to `reserved` as we can not use field ID 3 or 4 again in future in a comparable way.

**crypto_service.proto**
```
    /**
     * (NOT CURRENTLY SUPPORTED) Adds a livehash
     */
    rpc addLiveHash (Transaction) returns (TransactionResponse);

    /**
     * (NOT CURRENTLY SUPPORTED) Deletes a livehash
     */
    rpc deleteLiveHash (Transaction) returns (TransactionResponse);

    /**
     * (NOT CURRENTLY SUPPORTED) Retrieves a livehash for an account
     */
    rpc getLiveHash (Query) returns (Response);

    /**
     * (NOT CURRENTLY SUPPORTED) Returns the records of transactions recently funded by an account
     */
    rpc getFastTransactionRecord (Query) returns (Response);

    /**
     * (NOT CURRENTLY SUPPORTED) Retrieves the stakers for a node by account id
     */
    rpc getStakersByAccountID (Query) returns (Response);
```
I think these can just be removed.

There is also the state proof ones in 
**query_header.proto -> ResponseType**
```
    /**
     * (NOT YET SUPPORTED) Response returns both answer and state proof
     */
    ANSWER_STATE_PROOF = 1;

    /**
     * (NOT YET SUPPORTED) Response returns the total cost of answer and state proof
     */
    COST_ANSWER_STATE_PROOF = 3;
```
I think as these are enum values they can not be removed but we should check, maybe the most we can do is deprecate them.

**Comment by jsync-swirlds** [comment]
Stale.  Please reopen if still needed.
