### ISSUE TITLE
HIP 583 related doc comment needs to be updated

### ISSUE THREAD

**Issue by izik1** [hashgraph/hedera-protobufs#275]
Before [HIP-583](https://github.com/hashgraph/hedera-improvement-proposal/blob/main/HIP/hip-583.md) was finalized there was an edit made to remove mention of "alias key"s (they ended up not being supported? Not sure, doesn't matter to me) the language used in this repo still mentions them.

https://github.com/hashgraph/hedera-protobufs/blob/c1de1a199d11e6ace89679af9e4500cb92eb841c/services/crypto_create.proto#L157-L170

was changed to:
https://github.com/hashgraph/hedera-improvement-proposal/blob/main/HIP/hip-583.md#hapi-changes
(which I have written below).
```pb
message CryptoCreateTransactionBody {
	...
	/**
     * The bytes to be used as the account's alias. 
     *
     * The bytes must be formatted as the calcluated last 20 bytes of the
     * keccak-256 of the ECDSA primitive key.</li>
     *
     * All other types of keys, including but not limited to ED25519, ThresholdKey, KeyList, ContractID, and
     * delegatable_contract_id, are not supported.
     *
     * At most only one account can ever have a given alias on the network.
     */
	bytes alias = 18;
}
```

**Comment by jsync-swirlds** [comment]
The specification text is substantially rewritten and much clearer.
Please reopen this issue with additional detail if the updated specification remains unclear or incorect.
