### ISSUE TITLE
Add proto for TSS Roster

### ISSUE THREAD

**Issue by kfa-aguda** [hashgraph/hedera-protobufs#392]
As part of TSS Roster effort, a protobuf is required for a RosterEntry object that will be stored in the state, as well as updates to the state to store the roster entries.

As a part of this story, all protobuf models mentioned in the TSS-Roster design document need to be implemented. For a complete list, see https://github.com/hashgraph/hedera-services/pull/14045

**Comment by anthony-swirldslabs** [comment]
Please add a link to a merged PR before closing this story.
