### ISSUE TITLE
Bug: Wrong import on `services/transaction_body.proto`

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-protobufs#422]
### Description

When using the latest version (`main` branch) of the protobuf on the `block node` the generation process fails with the following error:

```
Import "auxiliary/tss/tss_message.proto" in proto file "/Users/user/Projects/hedera-block-node/stream/build/hedera-protobufs/services/transaction_body.proto" can not be found in src files.

```

### Steps to reproduce

Try to Generate using `./gradlew :stream:assemble`  on the block node repo.

### Additional context

![image](https://github.com/user-attachments/assets/b80e9b29-d808-4793-ac57-1bc9b4d6504d)

issue was introduced in this [PR](https://github.com/hashgraph/hedera-protobufs/commit/4c8fa91d1f625a5098dbc28e9dd74de6c9328790)

### Hedera network

other

### Version

v0.21.0-SNAPSHOT

### Operating system

None

**Comment by jsync-swirlds** [comment]
Please check hedera-services copy of these files to make sure those are correct as well.
