### ISSUE TITLE
freshdesk ticket 3411: Need to create a service account

### ISSUE THREAD

**Issue by andrewb1269hg** [hashgraph/hedera-protobufs#432]
Need to create a service account in hedera-protobufs repo

Need to create Github Service Account: hedera-protobufs-automation. Highest level of access: Write

Created by @rbarkerSL 

freshdesk ticket 3411 here: https://swirldslabs.freshdesk.com/a/tickets/3411

**Comment by andrewb1269hg** [comment]
Andrew and Roger to work on this issue together.

**Comment by rbarkerSL** [comment]
I believe the remaining effort is to update the workflows to use GH_ACCESS_TOKEN where needed

@mishomihov00 let's chat about this

**Comment by mishomihov00** [comment]
@rbarkerSL do we need to do anything here or it's already done?

**Comment by rbarkerSL** [comment]
> @rbarkerSL do we need to do anything here or it's already done?

On this PR I think we're done. However, I believe that we need to update Hedera Services  [node-flow-deploy-release-artifact.yaml](https://github.com/hashgraph/hedera-services/blob/e20b66ae32012a018bf82ae4913966966ce2a00c/.github/workflows/node-flow-deploy-release-artifact.yaml) to use the new secrets in services
- PROTOBUFS_GH_ACCESS_TOKEN
- PROTOBUFS_GPG_KEY_CONTENTS
- PROTOBUFS_GPG_KEY_PASSPHRASE
- PROTOBUFS_GPG_USER_EMAIL

I am creating a new issue in that repository for this.

**Comment by rbarkerSL** [comment]
This issue will be finished in [Hedera Services #17066](https://github.com/hashgraph/hedera-services/issues/17066)
