### ISSUE TITLE
Add Repo Maintainers to CODEOWNERS file

### ISSUE THREAD

**Issue by andrewb1269hg** [hashgraph/hedera-protobufs#456]
# Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Description**:

Update this repositories `.github/CODEOWNER` file to ensure that the repository maintainer
group(s) have full control of the files in this repository.

**Comment by andrewb1269hg** [comment]
We should modify .github/CODEOWNERS and include the catchall rule and the standard core rules.

The groups here should be:

@hashgraph/devops-ci
@hashgraph/release-engineering-managers
@hashgraph/developer-advocates 
@hashgraph/platform-base 
@hashgraph/platform-data 
@hashgraph/platform-hashgraph

**Comment by jsync-swirlds** [comment]
Platform has almost no interaction with protobufs.
SDKs, Block Node, Mirror Node, and Services are the primary entities that need to know when protobufs are changing and approve those changes.

**Comment by lpetrovic05** [comment]
> Platform has almost no interaction with protobufs. SDKs, Block Node, Mirror Node, and Services are the primary entities that need to know when protobufs are changing and approve those changes.

Events are in protobuf, this is a platform concern
